name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller pandas openpyxl

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --add-data "comedogenic_db.xlsx;." comedogenic_tester_gui.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ComedogenicTester
          path: dist/comedogenic_tester_gui.exe
